### ISSUE TITLE
New fork `swagger-typescript-api-nextgen` with extra features and fixes

### ISSUE THREAD

**Issue by grandsilence** [acacode/swagger-typescript-api#360]
Please check out my fork: [swagger-typescript-api-nextgen](https://github.com/grandsilence/swagger-typescript-api-nextgen), maybe it will be useful for those who need a secure version with updated dependencies, as well as support for current axios and other fixes.  
  
The package is present in the [npm (swagger-typescript-api-nextgen)](https://www.npmjs.com/package/swagger-typescript-api-nextgen).  
  
## ✨ The fork key differences

- Axios v0.27.2+ support
- Updated dependencies to eliminate vulnerabilities
- Merged features and fixes from `next` to `master` and some commits from origin pull requests:
  - Docs: added "generateClient", "typePrefix", "typeSuffix" options to readme for NodeJS usage (#335)
  - Feature: add an option to disable throwing an error when request.ok is not true (#297)
  - Feature: add a parameter to sort types and types properties (#299)
  - Feature: load prettier config from your project by default (#286)
  - Feature: allow passing "patch" option to "swagger2openapi" (#283)
  - Fix: missing `title` of object type (#303)
  - Fix: reject and exit with code 1 if error (#295)
  - Fix: missing extractRequestBody field in type
  - Fix: problem with missing HttpResponse type with --to-js option
  - Fix: unable to cancel fetch request with AbortSignal (#329)

**Comment by andersfylling** [comment]
Is there a reason these changes aren't a PR for swagger-typescript-api project?

**Comment by bartvanandel** [comment]
Looks like recently, activity is returning to this repo. Maybe this would be a good time to have the changes merged back into this original repo?

**Comment by js2me** [comment]
Hi @grandsilence , your fork looks good !   
This project is not abandoned, just I was not have a free time to work on it :)   
If you want to improve your fork, please merge the latest version of swagger-typescript-api, cause I fixed a lot of bugs and add a lot of features :)

**Comment by moteey** [comment]
Hi @js2me,
First of all, thanks for the great work on the generator.

I am currently using the nextgen package, but would love to switch back to the original one. That being said, the main reason I started using the `swagger-typescript-api-nextgen` was [this change](https://github.com/grandsilence/swagger-typescript-api-nextgen/commit/e918dd03bedccb38229219c120f8951402b6a3d3):

**templates/base/http-clients/axios-http-client.eta**
``` git
- import axios, { AxiosInstance, AxiosRequestConfig, AxiosResponse, ResponseType } from "axios";
+ import type { AxiosInstance, AxiosRequestConfig, AxiosResponse, ResponseType } from "axios";
+ import axios from "axios";
```

For my project, not using `type` modifiers for type-only imports throws errors, because of the following `tsconfig.json` options:
``` json
{
  "compilerOptions": {
    "preserveValueImports": true,
    "importsNotUsedAsValues": "error",
  }
}
```


Is there any chance this could make it into one of the following versions?
