### ISSUE TITLE
Is it possible to redefine the type of the returned value?

### ISSUE THREAD

**Issue by bezvrednyy** [acacode/swagger-typescript-api#417]
Is it possible to redefine the type of the returned value?
I want to use [Either monad.](https://github.com/JSMonk/sweet-monads/tree/master/either) To do this, in `httpClient.instance.interceptors.response`, I wrap everything in Either object. But I need to report this to typescript somehow.

I would like to generate something like this:
```
interface RightResponse {
  id: string,
}

type Error = 'invalid-password'|'user-non-exist'

login: (data: LoginAndPass, params: RequestParams = {}) => this.http.request<Either<RightResponse, Error>>
```

**Comment by marko-hologram** [comment]
Can you maybe just update the HTTP client template that you are generating? For example, here is the default fetch client template and `request` method that's defined on it https://github.com/acacode/swagger-typescript-api/blob/master/templates/base/http-clients/fetch-http-client.ejs#L157

Can you maybe just update this method's return type to this `Promise<HttpResponse<<Either<T, Error>, E>>`?. I'm not a Typescript wizard, I just replaced `T` with `Either<T, Error>` in this return type.

Not sure if that would fit your case because I see you have specific `Error` type here that is corresponding to this login request, but what I suggested doesn't apply to a specific API endpoint, it applies to all code that uses `request` method.

**Comment by js2me** [comment]
Hi @bezvrednyy ! This project use template driven development and you can customize almost everything with using custom templates (`--templates` option)
