### ISSUE TITLE
Content-Type: "multipart/form-data" is ignored

### ISSUE THREAD

**Issue by inomn** [acacode/swagger-typescript-api#671]
In generated axios http-API client there's a line

```
headers: {
        ...(requestParams.headers || {}),
        ...(type && type !== ContentType.FormData ? { "Content-Type": type } : {}),
      },
```

this prevents us from sending a request with content-type multipart/form-data.
Could anyone tell me what the reason was for this solution?

Replacing this with a simple 

```
      headers: {
        ...(requestParams.headers || {}),
        "Content-Type": type
      },
```

fixes the issue

**Comment by Isola92** [comment]
I think the header is applied automatically by the browser when passing a formdata object in the body.

**Comment by inomn** [comment]
@Isola92 Not the case for Axios + latest Chrome

**Comment by ThomasGuenard** [comment]
Same behavior using react-native:

We have to pass content-type with the header param to be able to send form-data.
As the generated request have already the type, it is sad to redefined it manually

**Comment by cf-dlangston** [comment]
It seems like the change adding this `...(type && type !== ContentType.FormData ? { "Content-Type": type } : {}),` was part of PR #173. The rationalization in the PR being:
>It's better to let the browser handle setting of this content-type, since it will add the correct boundary.

This corroborates what @Isola92 is saying. To fix I think it makes sense remove this check from the [`axios-http-client.ejs`](https://github.com/acacode/swagger-typescript-api/blob/c166ca8060bb956c25a4bc936513b323f404c385/templates/base/http-clients/axios-http-client.ejs#L130) template since axios doesn't automatically add this header. I just submitted PR #831 which does this.
