### ISSUE TITLE
Version 13.0.10 doesn't respect `onInsertPathParam` hook

### ISSUE THREAD

**Issue by ramondeklein** [acacode/swagger-typescript-api#806]
I'm using the following custom configuration:
```javascript
module.exports = {
  hooks: {
    onInsertPathParam: (paramName) => `encodeURIComponent(${paramName})`,
  },
};
```
This encodes all parameters using `encodeURIComponent` in the URL path. This works great with v13.0.9, but it doesn't work with v13.0.10 anymore.

This is generated with v13.0.9:
```typescript
    deleteBucket: (name: string, params: RequestParams = {}) =>
      this.request<void, ApiError>({
        path: `/buckets/${encodeURIComponent(name)}`,
        method: "DELETE",
        secure: true,
        ...params,
      }),
```

This is generated with v13.0.10:
```typescript
    deleteBucket: (name: string, params: RequestParams = {}) =>
      this.request<void, ApiError>({
        path: `/buckets/${name}`,
        method: "DELETE",
        secure: true,
        ...params,
      }),
```

**Comment by shrpne** [comment]
Loading of custom config is broken in 13.0.10, downgrading to 13.0.9 should help

@smorimoto
Probably replacing `require()` with `import()` should fix it [index.js#L304](https://github.com/acacode/swagger-typescript-api/blob/main/index.js#L304)
Also it is a good idea to display an error instead of hiding it [index.js#L306](https://github.com/acacode/swagger-typescript-api/blob/main/index.js#L306)

**Comment by smorimoto** [comment]
I'm away from home today and can't deal with this right away, so the patch is very welcome.

**Comment by ramondeklein** [comment]
This fix didn't solve our issue. It's still broken with 13.0.12.

**Comment by shrpne** [comment]
@ramondeklein it should be fixed in next release, until in released you can do one of:
- install latest commit from github `npm i acacode/swagger-typescript-api`
- don't export default and export named instead `export const hooks = {onInsertPathParam: () => {}}`
